"""
Neo4j 知识图谱导出器

负责导出 Neo4j 图数据库中的节点和关系
"""

import logging
import time
from pathlib import Path
from typing import Optional

from archive.exporters.base import BaseExporter, ExportResult
from config.settings import settings

logger = logging.getLogger(__name__)


class Neo4jExporter(BaseExporter):
    """Neo4j 知识图谱导出器"""

    name = "neo4j"
    description = "Neo4j 知识图谱导出器"

    # 连接重试配置
    MAX_RETRIES = 3
    RETRY_DELAY = 1.0

    def __init__(
        self,
        output_dir: str,
        uri: str = None,
        user: str = None,
        password: str = None,
        database: str = None,
    ):
        """
        初始化 Neo4j 导出器

        Args:
            output_dir: 输出目录
            uri: Neo4j URI
            user: 用户名
            password: 密码
            database: 数据库名称
        """
        super().__init__(output_dir)
        self.uri = uri or settings.NEO4J_URI
        self.user = user or settings.NEO4J_USER
        self.password = password or settings.NEO4J_PASSWORD
        self.database = database or getattr(settings, "NEO4J_DB", "neo4j")
        self.enabled = settings.ENABLE_NEO4J

    def _get_driver(self, retries: int = None):
        """
        获取 Neo4j 驱动，支持重试

        Args:
            retries: 重试次数

        Returns:
            Neo4j 驱动
        """
        from neo4j import GraphDatabase

        retries = retries or self.MAX_RETRIES
        last_error = None

        for attempt in range(retries):
            try:
                driver = GraphDatabase.driver(
                    self.uri,
                    auth=(self.user, self.password),
                )
                # 验证连接
                driver.verify_connectivity()
                self.logger.debug(f"Neo4j 连接成功 (尝试 {attempt + 1}/{retries})")
                return driver
            except Exception as e:
                last_error = e
                self.logger.warning(
                    f"Neo4j 连接失败 (尝试 {attempt + 1}/{retries}): {e}"
                )
                if attempt < retries - 1:
                    time.sleep(self.RETRY_DELAY)

        raise last_error

    def export(self) -> ExportResult:
        """导出 Neo4j 数据"""
        if not self.enabled:
            self.logger.info("Neo4j 未启用，跳过导出")
            return ExportResult(
                success=True,
                data=None,
                stats={"enabled": False},
            )

        try:
            driver = self._get_driver()
            output_file = Path(self.output_dir) / "neo4j.cypher"

            with driver.session(database=self.database) as session:
                # 统计节点和关系数量
                node_count = self._count_nodes(session)
                relation_count = self._count_relations(session)

                # 导出数据
                cypher_script = self._generate_cypher_script(session)

            driver.close()

            # 写入文件
            with open(output_file, "w", encoding="utf-8") as f:
                f.write(cypher_script)

            self.logger.info(
                f"已导出 Neo4j 数据: {node_count} 节点, {relation_count} 关系"
            )

            return ExportResult(
                success=True,
                data="neo4j.cypher",
                stats={
                    "enabled": True,
                    "node_count": node_count,
                    "relation_count": relation_count,
                },
            )

        except ImportError:
            self.logger.warning("neo4j 库未安装，跳过导出")
            return ExportResult(
                success=True,
                data=None,
                stats={"enabled": False, "error": "neo4j 库未安装"},
            )
        except Exception as e:
            self.logger.error(f"导出 Neo4j 数据失败: {e}")
            return ExportResult(success=False, error=str(e))

    def _count_nodes(self, session) -> int:
        """统计节点数量"""
        try:
            result = session.run("MATCH (n) RETURN count(n) AS count")
            record = result.single()
            return record["count"] if record else 0
        except Exception:
            return 0

    def _count_relations(self, session) -> int:
        """统计关系数量"""
        try:
            result = session.run("MATCH ()-[r]->() RETURN count(r) AS count")
            record = result.single()
            return record["count"] if record else 0
        except Exception:
            return 0

    def _generate_cypher_script(self, session) -> str:
        """
        生成 Cypher 脚本

        Args:
            session: Neo4j session

        Returns:
            Cypher 脚本内容
        """
        lines = []
        lines.append("// Neo4j Knowledge Graph Export")
        lines.append("// Generated by Ember Archive System")
        lines.append("")

        # 导出节点
        lines.append("// === Nodes ===")
        lines.append("")

        try:
            # 获取所有节点
            result = session.run("MATCH (n) RETURN n")
            for record in result:
                node = record["n"]
                labels = list(node.labels)
                properties = dict(node)

                if labels and properties:
                    label_str = ":".join(labels)
                    props_str = self._format_properties(properties)
                    lines.append(f"CREATE ({label_str} {props_str});")

        except Exception as e:
            self.logger.error(f"导出节点失败: {e}")

        # 导出关系
        lines.append("")
        lines.append("// === Relations ===")
        lines.append("")

        try:
            # 获取所有关系
            result = session.run(
                "MATCH (a)-[r]->(b) "
                "RETURN a.name AS from_name, type(r) AS rel_type, b.name AS to_name, properties(r) AS props"
            )
            for record in result:
                from_name = record["from_name"] or ""
                rel_type = record["rel_type"] or ""
                to_name = record["to_name"] or ""
                props = record["props"]

                # 转义名称
                from_name_escaped = self._escape_cypher_string(from_name)
                to_name_escaped = self._escape_cypher_string(to_name)

                props_str = ""
                if props:
                    props_str = " " + self._format_properties(props)

                lines.append(
                    f"MATCH (a {{name: '{from_name_escaped}'}}), (b {{name: '{to_name_escaped}'}}) "
                    f"CREATE (a)-[:{rel_type}{props_str}]->(b);"
                )

        except Exception as e:
            self.logger.error(f"导出关系失败: {e}")

        return "\n".join(lines)

    def _format_properties(self, properties: dict) -> str:
        """
        格式化属性为 Cypher 格式

        Args:
            properties: 属性字典

        Returns:
            Cypher 格式的属性字符串
        """
        items = []
        for key, value in properties.items():
            if value is None:
                items.append(f"{key}: null")
            elif isinstance(value, bool):
                items.append(f"{key}: {str(value).lower()}")
            elif isinstance(value, (int, float)):
                # 处理特殊浮点数
                if isinstance(value, float):
                    if value != value:  # NaN
                        items.append(f"{key}: NaN")
                    elif value == float("inf"):
                        items.append(f"{key}: Infinity")
                    elif value == float("-inf"):
                        items.append(f"{key}: -Infinity")
                    else:
                        items.append(f"{key}: {value}")
                else:
                    items.append(f"{key}: {value}")
            elif isinstance(value, str):
                escaped = self._escape_cypher_string(value)
                items.append(f"{key}: '{escaped}'")
            elif isinstance(value, list):
                # 处理列表
                list_items = []
                for item in value:
                    if item is None:
                        list_items.append("null")
                    elif isinstance(item, bool):
                        list_items.append(str(item).lower())
                    elif isinstance(item, (int, float)):
                        list_items.append(str(item))
                    elif isinstance(item, str):
                        escaped = self._escape_cypher_string(item)
                        list_items.append(f"'{escaped}'")
                    else:
                        escaped = self._escape_cypher_string(str(item))
                        list_items.append(f"'{escaped}'")
                items.append(f"{key}: [{', '.join(list_items)}]")
            elif isinstance(value, dict):
                # 嵌套字典转为字符串
                escaped = self._escape_cypher_string(str(value))
                items.append(f"{key}: '{escaped}'")
            else:
                # 其他类型转为字符串
                escaped = self._escape_cypher_string(str(value))
                items.append(f"{key}: '{escaped}'")

        return "{" + ", ".join(items) + "}"

    def _escape_cypher_string(self, s: str) -> str:
        """
        转义 Cypher 字符串中的特殊字符

        Args:
            s: 原始字符串

        Returns:
            转义后的字符串
        """
        if not s:
            return ""

        result = s
        # Cypher 特殊字符转义
        result = result.replace("\\", "\\\\")  # 反斜杠 (必须先处理)
        result = result.replace("'", "\\'")  # 单引号
        result = result.replace('"', '\\"')  # 双引号
        result = result.replace("\n", "\\n")  # 换行符
        result = result.replace("\r", "\\r")  # 回车符
        result = result.replace("\t", "\\t")  # 制表符
        result = result.replace("\b", "\\b")  # 退格符
        result = result.replace("\f", "\\f")  # 换页符
        result = result.replace("\0", "\\0")  # NULL字符

        return result
